source:
  datasource: main
  sql_query: |
    SELECT maintenance_id FROM shop_maintenance
  incremental_field: update_time
index:
  name: maintenance
  analyzer: jieba_std
  search_analyzer: jieba_search
  fields:
    maintenance_id: { type: keyword, filter: true }
